version: '3.6'
services:
  backend:
    image: "node:16-alpine"
    user: "node"
    hostname: "backend"
    working_dir: "/home/node/app"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Warsaw
      - EMAIL=dariusz.majnert@gmail.com
    volumes:
      - ./backend:/home/node/app
    expose:
      - "3001"
    restart: unless-stopped
    command: "npm start"
    networks:
      - czogori-network
  proxy:
    image: "nginx:stable-alpine"
    volumes:
      - ./web/build:/web
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - czogori-network

networks:
  czogori-network:
    driver: bridge
